# =============================================
#  PROD PROFILE — all secrets from env vars
# =============================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.pool-name=HospitalHikariPool-Prod
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

logging.level.com.adags.hospital=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.security=WARN

# Swagger UI disabled in production
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
